# kustomization.yaml
resources:
  - ./secrets/extern-user1-sealedsecret.yaml
  - deploy.yaml
#helmCharts:
#  - name: kafka
#    repo: https://charts.bitnami.com/bitnami
#    version: 26.7.2
#    releaseName: kafka
#    namespace: kafka
#    valuesFile: values.yaml

helmCharts:
  - name: my-kafka-chart
    releaseName: lokal
    namespace: kafka
    valuesFile: values.yaml
