apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
      - name: my-app2
        image: alpine:3.11