apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
{{- range $i, $n := until (.Values.appCount | int) }}
          - name: app{{ add $n 1 }}
{{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}'
    spec:
      project: appsets
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{name}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
