apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
{{- range $i, $n := until (.Values.appCount | int) }}
          - name: app{{ add $n 1 }}
{{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}'
    spec:
      project: appset
      source:
        repoURL: git@github.com:adilosch/kubernetes-deployment.git
        targetRevision: main
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{name}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
