kafka:
  topics:
    - name: topic-one
      partitions: 1
      replicas: 1
      retentionMs: 604800000  # 7 days in milliseconds
    - name: topic-two
    - name: topic-three
      partitions: 1
      retentionMs: 259200000  # 3 days in milliseconds

