kafka:
  users:
    - name: user-one
      acl:
        - topic: topic-one
          permissions:
            - read
        - topic: topic-one
          permissions:
            - write
    - name: user-two
      acl:
        - topic: topic-two
          permissions:
            - read
    - name: user-three
      acl:
        - topic: topic-three
          permissions:
            - write
