kafka:
  users:
    - name: user-one
      acl:
        - topic: topic-one
          permissions:
            - READ
            - WRITE
    - name: user-two
      acl:
        - topic: topic-two
          permissions:
            - READ
    - name: user-three
      acl:
        - topic: topic-three
          permissions:
            - WRITE

