nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - kind: Deployment
    version: v1
    path: spec/template/spec/containers[]/envFrom[]/configMapRef/name
  - kind: Deployment
    version: v1
    path: spec/template/spec/containers[]/env[]/valueFrom/configMapKeyRef/name