namePrefix: dev-


resources:
  - ../../base/
  - ./hooks/pre_delete_hook.yaml

replicas:
  - name: nginx
    count: 1

images:
  - name: nginx
    newTag: "1.25-alpine"


configurations:
  - kustomizeconfig.yaml