# kustomization.yaml
resources:
- ../../base

#namespace: prod
namePrefix: feature2-

commonLabels:
  app: service1
  version: feature2

# Patch using Path JSON6902: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-path-json6902     
patches:
  - patch: |-
      kind: VirtualService
      apiVersion: networking.istio.io/v1alpha3
      metadata:
        name: service1
        namespace: helloworld
      spec:
        hosts:
          - feature2-service1.lan
        http:
          - route:
              - destination:
                  host: feature2-service1


images:
- name: nginx
  newName: nginx
  newTag: "3.9r3r3"