apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_env.yaml

namespace: prod
 
commonLabels:
  foo: bar
  
configMapGenerator:
  - name: app-config
    literals:
      - username=prod-user

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - password=foo

images:
- name: alpine
  newName: alpine
  newTag: "3.9"      