kafkaCluster: my-cluster

topics:
  - name: topic-b1
    partitions: 1
    replicas: 1
    retentionMs: 604800000  # 7 Tage
    acls:
      - user: team-b-service
        permissions: Write
      - user: team-a-service  # Team A beantragt diese Berechtigung per Pull Request!
        permissions: Read

  - name: topic-b2
    partitions: 1
    replicas: 1
    retentionMs: 259200000  # 3 Tage
    acls:
      - user: team-b-service
        permissions: Read
      - user: team-a-service
        permissions: Write
