kafkaUsers:
  user-one:
    acls:
      - resourceType: "topic"
        resourceName: "example-topic"
        operation: "Read"
      - resourceType: "topic"
        resourceName: "example-topic"
        operation: "Write"
  user-two:
    acls:
      - resourceType: "group"
        resourceName: "example-consumer-group"
        operation: "Read"


