kafkaUsers:
  user1:
    acls:
      - resourceType: "topic"
        resourceName: "example-topic"
        operation: "Read"
      - resourceType: "topic"
        resourceName: "example-topic"
        operation: "Write"


