namespace: kafka
kafkaCluster: my-cluster

kafkaUsers:
  - name: team-a-service
    acls:
      - topic: topic-b1
        permissions: Write
      - topic: topic-b2
        permissions: Read, Write
  - name: team-b-service
    acls:
      - topic: topic-b1
        permissions: Read
