# values.yaml
users:
  - name: user-one
    acls:
      - topic: topic-a
        operation: Read
      - topic: topic-b
        operation: Write
  - name: user-two
    acls:
      - topic: topic-c
        operation: Read
      - topic: topic-d
        operation: Write
  - name: user-three
    # No ACLs defined for user-three, default ACL (Read on all topics) will be applied
