# values.yaml
kafkaUsers:
  - name: user-one
    acls:
      - topic: topic-a
        operation: Write
      - topic: topic-b
        operation: Read, Write
  - name: user-two
    acls:
      - topic: topic-a
        operation: Read
      - topic: topic-c
        operation: Write
  - name: user-three
    acls:
      - topic: topic-b
        operation: Read, Write
