{{- range .Values.kafka.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: "{{ . }}"
  labels:
    strimzi.io/cluster: si-cluster
spec:
{{- if hasPrefix "extern." . }}
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: {{ . }}
          key: password
{{- end }}
  authorization:
    type: simple
    acls:
{{- range $.Values.kafka.acls }}
      - resource:
          type: topic
          name: {{ .topic }}
          patternType: literal
        operations:
{{ toYaml .permissions | indent 10 }}
        host: "*"
{{- end }}
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
---
{{- end }}
